### ISSUE TITLE
Conflict with "TEI - GPS Distance Helper" mod

### ISSUE THREAD

**Issue by JamesMortimer** [StarCpt/SE-GpsFolders#1]
Thanks for making this! Hope this report helps.

This conflicts with TEI - GPS Distance Helper - https://steamcommunity.com/workshop/filedetails/?id=1223617082, and presumably also the parent mod that was forked from. Both tries to re-write the description, but it expects to always be first. It tries to include distance in [] at the first, while this adds a XML tag for the folder. Result is that the distance mod works, but the folder mod does not. However, this plugin makes TEI - GPS Distance Helper obsolete, so if using this, that should simply not be used.

Suggest adding this as a known conflict at the bottom of the the github main page with workaround to just not use the other mod.

**Comment by StarCpt** [comment]
Incompatible mods added to readme
